add log

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -13,16 +13,16 @@ DATABASE_NAME=${DATABASE_NAME:-test_db}
 
 # If running the rails server then create or migrate existing database
 if [ "${@: -2:1}" == "./bin/rails" ] && [ "${@: -1:1}" == "server" ]; then
-  # echo "Preparing database..."
-  # ./bin/rails db:prepare || { echo 'db:prepare failed' ; exit 1; }
+  echo "Preparing database..."
+  ./bin/rails db:prepare || { echo 'db:prepare failed' ; exit 1; }
 
-  echo "Migrating database..."
-  ./bin/rails db:migrate || { echo 'db:migrate failed' ; exit 1; }
+  # echo "Migrating database..."
+  # ./bin/rails db:prepare || { echo 'db:migrate failed' ; exit 1; }
 
-  echo "Listing tables in the database..."
+  echo "Listing status of the database..."
  # Check i  f Rails can connect to the database
   # echo "Checking database connection..."
-  # RAILS_ENV=production ./bin/rails dbconsole -c || { echo 'Database connection failed' ; exit 1; }
+  ./bin/rails db:migrate:status || { echo 'Database status failed' ; exit 1; }
 
   echo "Installing solid_cache..."
   ./bin/rails solid_cache:install || { echo 'solid_cache:install failed' ; exit 1; }
