Add comand to install cache

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -13,7 +13,12 @@ DATABASE_NAME=${DATABASE_NAME:-test_db}
 
 # If running the rails server then create or migrate existing database
 if [ "${@: -2:1}" == "./bin/rails" ] && [ "${@: -1:1}" == "server" ]; then
-  ./bin/rails db:prepare
+  echo "Preparing database..."
+  ./bin/rails db:prepare || { echo 'db:prepare failed' ; exit 1; }
+
+  echo "Installing solid_cache..."
+  ./bin/rails solid_cache:install || { echo 'solid_cache:install failed' ; exit 1; }
+
 
   # ./bin/rails admin:create RAILS_ENV=production
 fi
