Add step to log if db exists

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -19,6 +19,11 @@ if [ "${@: -2:1}" == "./bin/rails" ] && [ "${@: -1:1}" == "server" ]; then
   echo "Migrating database..."
   ./bin/rails db:migrate || { echo 'db:migrate failed' ; exit 1; }
 
+  echo "Listing tables in the database..."
+ # Check i  f Rails can connect to the database
+  # echo "Checking database connection..."
+  # RAILS_ENV=production ./bin/rails dbconsole -c || { echo 'Database connection failed' ; exit 1; }
+
   echo "Installing solid_cache..."
   ./bin/rails solid_cache:install || { echo 'solid_cache:install failed' ; exit 1; }
 
