Remove cache for now as it needs its own database

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -16,8 +16,8 @@ if [ "${@: -2:1}" == "./bin/rails" ] && [ "${@: -1:1}" == "server" ]; then
   echo "Preparing database..."
   ./bin/rails db:prepare || { echo 'db:prepare failed' ; exit 1; }
 
-  echo "Installing solid_cache..."
-  ./bin/rails solid_cache:install || { echo 'solid_cache:install failed' ; exit 1; }
+  # echo "Installing solid_cache..."
+  # ./bin/rails solid_cache:install || { echo 'solid_cache:install failed' ; exit 1; }
 
 
   # ./bin/rails admin:create RAILS_ENV=production
