add command to run migartions

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -13,8 +13,11 @@ DATABASE_NAME=${DATABASE_NAME:-test_db}
 
 # If running the rails server then create or migrate existing database
 if [ "${@: -2:1}" == "./bin/rails" ] && [ "${@: -1:1}" == "server" ]; then
-  echo "Preparing database..."
-  ./bin/rails db:prepare || { echo 'db:prepare failed' ; exit 1; }
+  # echo "Preparing database..."
+  # ./bin/rails db:prepare || { echo 'db:prepare failed' ; exit 1; }
+
+  echo "Migrating database..."
+  ./bin/rails db:migrate || { echo 'db:migrate failed' ; exit 1; }
 
   echo "Installing solid_cache..."
   ./bin/rails solid_cache:install || { echo 'solid_cache:install failed' ; exit 1; }
