Add authentication when downloading pact consumer json as repo is now private

diff --git a/.github/workflows/pact_tests.yml b/.github/workflows/pact_tests.yml
--- a/.github/workflows/pact_tests.yml
+++ b/.github/workflows/pact_tests.yml
@@ -48,17 +48,42 @@ jobs:
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install -y jq
 
+      - name: Debug API response
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            https://api.github.com/repos/fpezcara/book-tracker-ui/releases/tag/pact-latest)
+          echo "$RESPONSE" | jq '.' || { echo "Invalid JSON response"; echo "$RESPONSE"; exit 1; }
+
+      - name: Debug API response
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            https://github.com/fpezcara/book-tracker-ui/releases/tag/pact-latest)
+          echo "$RESPONSE" | jq '.' || { echo "Invalid JSON response"; echo "$RESPONSE"; exit 1; }
+  
+
       - name: Download pact file from consumer release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mkdir -p pact
 
           RELEASE_ID=$(curl -s \
-            https://github.com/fpezcara/book-tracker-ui/releases/tags/pact-latest \
+            https://api.github.com/repos/fpezcara/book-tracker-ui/releases/tag/pact-latest \
             | jq -r '.assets[] | select(.name | test("Book_Tracker_UI-Book_Tracker_API.json")) | .id')
 
+          if [ -z "$RELEASE_ID" ]; then
+            echo "Error: Pact release or asset not found."
+            exit 1
+          fi
+
           curl -L \
+            -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/octet-stream" \
-            https://github.com/fpezcara/book-tracker-ui/book-tracker-ui/releases/assets/$RELEASE_ID \
+            https://api.github.com/repos/fpezcara/book-tracker-ui/releases/assets/$RELEASE_ID \
             -o pact/Book_Tracker_UI-Book_Tracker_API.json
 
       - name: Start Rails server
